---
title: "Defenders"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(plyr)
library(dplyr)
```


## Data load and cleaning
```{r data load and cleaning, message=FALSE, warning=FALSE}
def_stat <- read.csv('plays_split.csv', header = TRUE, sep=',')

def_stat <- subset(def_stat, offenseFormation != '')
def_stat <- subset(def_stat, typeDropback != '')
def_stat$counts <- 1

def_stat$yardFromDefTouch <- 0
def_stat$yardFromDefTouch <- def_stat$yardlineNumber
def_stat$yardFromDefTouch[def_stat$possessionTeam == def_stat$yardlineSide] <- (100 - def_stat$yardlineNumber)

def_stat$success <- 0
def_stat$success[def_stat$playResult >= def_stat$yardsToGo] <- 1

def_stat$yard_zone <- 1
def_stat$yard_zone[def_stat$yardFromDefTouch<80] <- 2
def_stat$yard_zone[def_stat$yardFromDefTouch<40] <- 3
def_stat$yard_zone[def_stat$yardFromDefTouch<20] <- 4
```

## Preparing statistics
```{r statistic, message=FALSE, warning=FALSE}
groupColumns = c("offenseFormation","DL_def", "LB_def", "DB_def", "yard_zone","success")
dataCol = c("counts")

res <- ddply(def_stat, groupColumns, function(x) colSums(x[dataCol]))


single_grp_form <- aggregate(res$counts, by=list(offenseFormation=res$offenseFormation), FUN=sum)

all_grp <- aggregate(res$counts, by=list(offenseFormation=res$offenseFormation, 
                                          DL_def=res$DL_def, DB_def=res$DB_def, 
                                          DB_def=res$DB_def, yard_zone = res$yard_zone),  FUN=sum)


res <- res %>% rowwise %>% do({
  result = as_data_frame(.)
  
  result$countsOfFormation = single_grp_form[single_grp_form$offenseFormation == result$offenseFormation, 2]
  
  result$totalAll = all_grp[all_grp$offenseFormation == result$offenseFormation & 
                              all_grp$DL_def == result$DL_def &
                              all_grp$DB_def == result$DB_def & 
                              all_grp$DB_def == result$DB_def &
                              all_grp$yard_zone == result$yard_zone, 6]
  result
})

res <- res %>%
  rowwise %>%
  do({
    result = as_data_frame(.)
    result$Percentage = round ( (result$counts/(result$totalAll))*100 , 2)
    result
  })
```

## Predict
```{r predict}
question_ofeenseFormation <- 'EMPTY'
question_yardLineNumber <- 2

question_yard_zone <- 1
question_yard_zone[def_stat$yardFromDefTouch<80] <- 2
question_yard_zone[def_stat$yardFromDefTouch<40] <- 3
question_yard_zone[def_stat$yardFromDefTouch<20] <- 4

if (question_yardLineNumber >= 80){
    question_yard_zone <- 1
} else if (question_yardLineNumber < 80 && question_yardLineNumber > 40){
    question_yard_zone <- 2
} else if (question_yardLineNumber <= 40 && question_yardLineNumber > 20){
    question_yard_zone <- 3
}  else if (question_yardLineNumber <= 20){
    question_yard_zone <- 4 }

answer <- res[ which(res$offenseFormation==question_ofeenseFormation
                         & res$yard_zone == question_yard_zone), ]

answer <- answer[ which(answer$counts > 10), ]
answer <- answer[order(answer$success,-answer$Percentage, -answer$counts),]
answer <- answer[c(1,2,3,4,10)]
head(answer[1:5] , 3)
```